modify(ci-cd.yml): add check jest result

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -24,11 +24,22 @@ jobs:
           cd ./students/pei-tung/Canchu
           docker build -t canchu-server .
           docker-compose up -d
-      - name: Sleep for 100 seconds
-        run: sleep 100
+      - name: Sleep for 20 seconds
+        run: sleep 20
       - name: Run Test
         run: |
-          docker exec canchu-server npm test -- --watch=false
+          docker exec canchu-server npm test -- --watch=false --json --outputFile=test-results.json
+      - name: Check Jest test results
+        run: |
+          if [ -f "test-results.json" ]; then
+            npm install -g jq
+            passed=$(jq -r '.numPassedTests' test-results.json)
+            failed=$(jq -r '.numFailedTests' test-results.json)
+            if [ "$failed" -gt 0 ]; then
+              echo "Some tests failed! Take appropriate actions." && exit 1 
+            else
+              echo "All tests passed! Continue with the next actions." && exit 0
+            fi
 
   deploy:
     needs: test
