check(docker-image.yml):  .env file

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -26,6 +26,14 @@ jobs:
           cat .env
         env:
           ENV_FILE_PATH: ./students/pei-tung/Canchu/app
+      - name: Check if .env file exists
+        run: |
+          if [ -f "${ENV_FILE_PATH}/.env" ]; then
+            echo ".env file exists at ${ENV_FILE_PATH}"
+          else
+            echo ".env file not found at ${ENV_FILE_PATH}"
+            exit 1
+          fi
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v2
       - name: Set up Docker Buildx
